"""
Reads every saved transcript in recordings/ and asks an LLM (via the OpenAI
API) to flag likely bugs in the clinic agent's behavior, following the same
format the challenge doc's example bug report uses (Bug / Severity / Call /
Details).

This is a first pass, not a replacement for actually listening to the calls.
Treat its output as a draft: skim the audio for anything it flags as
Medium/High severity before including it in your final bug_report.md.

Usage:
    python -m src.bug_analyzer
"""

import json
from pathlib import Path

from openai import OpenAI

from src.config import load_settings

RECORDINGS_DIR = Path(__file__).resolve().parent.parent / "recordings"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "bug_report.md"

RUBRIC = """You are reviewing a transcript of a phone call. Two parties spoke:

- PATIENT_CALLER: our own automated test bot, playing a simulated patient.
  This is NOT what you are evaluating. Never flag anything this party says
  as a bug.
- CLINIC_AI_UNDER_TEST: the medical clinic's AI phone agent. This is the
  system being evaluated. All bugs you report must describe something THIS
  party said or did.

In the transcript JSON below, each turn has already been relabeled with a
"speaker" field set to either "PATIENT_CALLER" or "CLINIC_AI_UNDER_TEST" so
there is no ambiguity about who said what.

Check specifically for things CLINIC_AI_UNDER_TEST did wrong, such as:
- Confirming actions that should not be possible (e.g. booking outside office
  hours, confirming a service the clinic likely doesn't offer)
- Ignoring or mishandling information the patient already gave
- Failing to ask for information it clearly needs before proceeding
- Poor handling of interruptions or topic changes
- Contradicting itself within the same call
- Giving vague or evasive answers to direct questions (hours, insurance, etc.)
- Losing track of earlier parts of a multi-intent call
- Any hallucinated policy, price, or fact stated with false confidence

For each issue found, respond with a JSON array of objects with these keys:
- "bug": one-sentence description
- "severity": "Low", "Medium", or "High"
- "details": 2-4 sentences explaining what happened and why it's a problem
- "approx_location": a short quote from CLINIC_AI_UNDER_TEST showing where in
  the transcript it happened

If you find no genuine issues in what CLINIC_AI_UNDER_TEST said, return an
empty JSON array: []
Respond with ONLY the JSON array, no other text.
"""


def relabel_transcript(conversation: dict) -> list[dict]:
    """
    ElevenLabs labels our own test bot as role "agent" and the external
    party we called (the clinic's AI) as role "user", which is the opposite
    of what those words usually mean and reliably confuses an LLM reviewer.
    We relabel explicitly before sending anything to the model.
    """
    relabeled = []
    for turn in conversation.get("transcript", []):
        role = turn.get("role")
        speaker = "PATIENT_CALLER" if role == "agent" else "CLINIC_AI_UNDER_TEST"
        relabeled.append({"speaker": speaker, "message": turn.get("message", "")})
    return relabeled


def load_transcripts() -> list[tuple[str, dict]]:
    results = []
    for path in sorted(RECORDINGS_DIR.glob("*.transcript.json")):
        scenario_id = path.stem.replace(".transcript", "")
        data = json.loads(path.read_text())
        results.append((scenario_id, data))
    return results


def analyze_transcript(client: OpenAI, scenario_id: str, conversation: dict) -> list[dict]:
    relabeled = relabel_transcript(conversation)
    transcript_text = json.dumps(relabeled, indent=2)

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {
                "role": "user",
                "content": f"{RUBRIC}\n\nTranscript for scenario {scenario_id}:\n{transcript_text}",
            }
        ],
    )

    raw_text = response.choices[0].message.content or ""
    raw_text = raw_text.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()

    try:
        return json.loads(raw_text)
    except json.JSONDecodeError:
        print(f"[warn] Could not parse model output for {scenario_id}, skipping. Raw output:\n{raw_text}")
        return []


def write_report(all_bugs: list[tuple[str, dict]]) -> None:
    lines = ["# Bug Report", "", "Generated by src/bug_analyzer.py. Review before final submission.", ""]

    if not all_bugs:
        lines.append("No issues flagged by the automated pass.")
    else:
        for i, (scenario_id, bug) in enumerate(all_bugs, start=1):
            lines.append(f"## {i}. {bug.get('bug', 'Untitled issue')}")
            lines.append(f"**Severity:** {bug.get('severity', 'Unknown')}")
            lines.append(f"**Call:** {scenario_id}.transcript.txt / {scenario_id}.mp3")
            lines.append(f"**Location:** {bug.get('approx_location', 'n/a')}")
            lines.append("")
            lines.append(f"**Details:** {bug.get('details', '')}")
            lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {len(all_bugs)} flagged issues to {OUTPUT_PATH}")


def main() -> None:
    settings = load_settings()
    client = OpenAI(api_key=settings.openai_api_key)

    transcripts = load_transcripts()
    if not transcripts:
        print(f"No transcripts found in {RECORDINGS_DIR}. Run call_runner.py first.")
        return

    all_bugs: list[tuple[str, dict]] = []
    for scenario_id, conversation in transcripts:
        print(f"Analyzing {scenario_id}...")
        bugs = analyze_transcript(client, scenario_id, conversation)
        for bug in bugs:
            all_bugs.append((scenario_id, bug))

    write_report(all_bugs)


if __name__ == "__main__":
    main()